import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

SAVE_MODEL = True
LOAD_MODEL = False
TRAIN_MODEL = True
VALID_MODEL = True
TEST_MODEL = True

INPUT_SIZE = 1024

CLASS_LABELS = ["0", "1", "2"]
NUM_CLASSES = len(CLASS_LABELS)
NUM_SAMPLES_CLASS_0 = 50
NUM_SAMPLES_CLASS_1 = 325
NUM_SAMPLES_CLASS_2 = 264
SAMPLES_PER_CLASS = [NUM_SAMPLES_CLASS_0, NUM_SAMPLES_CLASS_1, NUM_SAMPLES_CLASS_2]
TOTAL_NUM_SAMPLES = sum(SAMPLES_PER_CLASS)

LEARNING_RATES = [1e-2, 1e-3, 1e-4, 1e-5]
WEIGHT_DECAY = 0.0
BATCH_SIZES = [1, 32, 64, 128, 256, 1024]
EPOCH_NUM = 10
EARLY_STOPPING_PATIENCE = 8

ASSET_DIR = "assets"
DATASET_DIR = "datasets"
CSV_FILE = "dataset.csv"
MODELS_DIR = "models"
LOG_DIR = "logs"
DIRECTORIES=[LOG_DIR]